### ISSUE TITLE
DESolver installation

### ISSUE THREAD

**Issue by octaviodario** [Microno95/desolver#1]
i installed DESolver on a macbook pro (macos high sierra v10.13.3, 2.3 GHz Intel Core i7) with:
python3 -m pip install DESolver
and everything went ok but i tried:
octavioDarioMacBookPro:~ octavioDario$ python3
Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import DESolver
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'DESolver'
>>> 
then, as you told to me, i tried:
octavioDarioMacBookPro:~ octavioDario$ python3
Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import desolver
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/desolver/__init__.py", line 1, in <module>
    from .differentialsystem import *
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/desolver/differentialsystem.py", line 35, in <module>
    import desolver.integrationschemes as ischemes
ModuleNotFoundError: No module named 'desolver.integrationschemes'
>>>

**Comment by Microno95** [comment]
Since you closed the issue I assume it's solved, if not then I'll reopen it and hopefully I can help you troubleshoot the issue.

**Comment by Microno95** [comment]
Though you closed the issue, I looked into it just now and it appears that the source files weren't being uploaded to pypi properly so now I have updated the version on PyPi to 1.5.2 and if you install that, then you should no longer run into the same problem.

**Comment by octaviodario** [comment]
hi:
the package was installed successfully!!!
kind regards from cuernavaca!!!
